# Generated by Django 5.2 on 2025-04-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default='POK_876557', max_length=10, primary_key=True, serialize=False),
        ),
    ]
