# Generated by Django 5.2 on 2025-04-16 19:17

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_id_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=products.models.generate_pid, max_length=10, primary_key=True, serialize=False),
        ),
    ]
